# Generated by Django 5.0.1 on 2024-01-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='detail',
            field=models.CharField(default='Default Detail Value', max_length=500),
        ),
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(default='noun', max_length=500),
        ),
    ]
