# Generated by Django 5.0.1 on 2024-01-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_feature_detail_feature_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='detail',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
